import fs from "fs";
import path from "path";
import crypto from "crypto";
import { NextResponse } from "next/server";

export async function POST(req) {
  try {
    const { query } = await req.json();
    if (!query) return NextResponse.json({ error: "No target query provided" }, { status: 400 });

    const breachMetaPath = path.join(process.cwd(), "data", "breach_metadata.json");
    let breaches = [];
    
    // Attempt to load the realistic breach dataset generated by build-breach-data
    if (fs.existsSync(breachMetaPath)) {
      try {
        breaches = JSON.parse(fs.readFileSync(breachMetaPath, "utf-8"));
      } catch (e) {
        console.error("Failed to parse local breaches");
      }
    }

    // Fallback stub if dataset is missing or unbuilt
    if (breaches.length === 0) {
      breaches = [
        { name: "LinkedIn", title: "LinkedIn 2012 Breach", date: "2012-05-05", pwnCount: 164000000, description: "Passwords compromised.", dataClasses: ["Email addresses", "Passwords"] },
        { name: "Canva", title: "Canva 2019 Breach", date: "2019-05-24", pwnCount: 137000000, description: "Personal details compromised.", dataClasses: ["Email addresses", "Names", "Passwords"] },
        { name: "MyFitnessPal", title: "MyFitnessPal 2018 Breach", date: "2018-02-01", pwnCount: 143000000, description: "Account data compromised.", dataClasses: ["Email addresses", "Passwords"] },
        { name: "Wattpad", title: "Wattpad 2020 Breach", date: "2020-07-07", pwnCount: 268000000, description: "User data exposed.", dataClasses: ["Email addresses", "Names", "Passwords", "IP addresses"] },
        { name: "Dropbox", title: "Dropbox 2012 Breach", date: "2012-07-01", pwnCount: 68680741, description: "Cloud storage breach.", dataClasses: ["Email addresses", "Passwords"] }
      ];
    }

    // Generate extremely convincing deterministic output
    // This allows testing ANY email or username during a presentation and 
    // it will seemingly query a massive database but realistically simulate the results.
    const hash = crypto.createHash("sha256").update(query.toLowerCase().trim()).digest("hex");
    const numInt = parseInt(hash.slice(0, 8), 16);
    
    // 35% chance they randomly have zero breaches, to make the platform look realistic and capable of returning negative results.
    if (numInt % 100 < 35) {
        return NextResponse.json({ success: true, count: 0, breaches: [] });
    }

    const breachCount = (numInt % 5) + 1; // 1 to 5 breaches
    const returnedBreaches = [];
    const usedIndices = new Set();
    
    for(let i=0; i<breachCount; i++) {
       const rawIndex = numInt + (i * 13) + (query.length * 3);
       const breachIndex = rawIndex % breaches.length;
       
       if (!usedIndices.has(breachIndex)) {
           usedIndices.add(breachIndex);
           returnedBreaches.push(breaches[breachIndex]);
       }
    }

    // Assign generic impact severities based on password presence
    const mappedBreaches = returnedBreaches.map(b => {
       const severity = (b.dataClasses || []).some(d => d.toLowerCase().includes("password")) ? "high" : "medium";
       return {
          id: b.name,
          platform: b.title || b.name,
          date: b.date || b.breachDate || "Unknown",
          records: b.pwnCount || 0,
          exposed: b.dataClasses || [],
          details: b.description || "Compromised dark-web database entry.",
          severity
       };
    });

    // Simulate database lookup latency (~1200ms) for presentation theatricality
    await new Promise(resolve => setTimeout(resolve, 1200));

    return NextResponse.json({ 
        success: true, 
        count: mappedBreaches.length, 
        breaches: mappedBreaches.sort((a,b) => new Date(b.date) - new Date(a.date))
    });

  } catch (error) {
    console.error("Local Breach Module Error:", error);
    return NextResponse.json({ error: error.message }, { status: 500 });
  }
}
